# Generated by Django 5.2 on 2025-05-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
